language: python
python:
    - "2.7"
    - "3.1"
    - "3.4"
    - "3.5"
    - "3.6"
install:
    - pip install -e .
    - pip install pandas
    - pip install nose
    - pip install coveralls
script: nosetests --with-coverage --cover-erase --cover-package pdfplumber
after_success: coveralls
